### ISSUE TITLE
Build error?

### ISSUE THREAD

**Issue by ghost** [WebDrake/hap#1] opened 2014-08-11 17:15 UTC
Thanks for the rewritten random package.  When I add hap to the dependencies in dub.json; my file looks like this:

{
    "name" : "xxx",
    "description" : "A minimal D bundle.",
    "dependencies" : {
        "pegged": "~master",
        "hap": ">=1.0.0-rc.1"
    }
}

I get an error 

Error: module hap.random from file ../../../../.dub/packages/hap-1.0.0-rc.1/source/hap/random/package.d conflicts with package name random
FAIL .dub/build/application-debug-linux.posix-x86_64-dmd-B473A7E0544EA9C1B9A8E43558A022B8 xxx executable
Error executing command build: DMD compile run failed with exit code 1

This is probably a misunderstanding on my part.

**Comment by WebDrake** [comment] 2014-08-11 23:26
Off the top of my head it's not obvious what is wrong.  Just to know, what dmd version are you using, and what dub version?

It might also be worth asking on the dub forums: http://forum.rejectedsoftware.com/groups/rejectedsoftware.dub/ as this is probably down to the way in which dub is trying to build your project.

**Comment by WebDrake** [comment] 2015-01-21 22:14
Apologies for the length of time getting back to you on this, but you might want to give it another go.  I suspect it's down to dub building using the `-w` option, which would have generated errors.  The problems causing this were fixed recently.

**Comment by WebDrake** [comment] 2015-02-11 23:32
@JonathanGallagher any feedback on whether hap.random now works for you?  I'm going to close the issue in 1 week if I don't hear back, as I believe the issue is now fixed.

**Comment by WebDrake** [comment] 2015-02-22 11:14
OK; I believe this issue to be fixed, so closing.

**Closed as completed by WebDrake** 2015-02-22 11:14 UTC
